### ISSUE TITLE
Feature Request: [Filter option] Hide Owned

### ISSUE THREAD

**Issue by xcpttrips** [Linj1k/fab_extended#2]
Problem with Fab: Many assets become Free long after their release, and as such they are difficult to filter for (the user can filter for Free and then scroll down thousands of entries an look out for any that aren't already owned).

Solution: An extended option would be useful that would hide owned assets - this of course would be best implemented by Epic, and it would be trivial, but we know, the likelihood is, they won't. Not sure how much can be injected with an extension, but even if owned items would just be grayed out or replaced by a blank rectangle in search results, this would make the process of hunting free assets, a lot more comfortable.

**Comment by Linj1k** [comment]
I don't know if this is really possible,
I'd try to do a few things, but given the way the site works, it could be complex if Epic doesn't do it themselves

**Comment by Linj1k** [comment]
I've tried a number of options, but unfortunately they all break the site,
It would be better if Fab.com did it themselves.

**Comment by xcpttrips** [comment]
Thanks for trying and big thanks for implementing the other suggestions!

**Comment by adnoh** [comment]
@Linj1k 
What about an additonal button to autoclaim which executes some xpath - I help me with the following at the moment
`
var xpath = "//div[contains(text(),'Saved in My Library')]";
var result = document.evaluate(xpath, document, null,  XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null)
for (i=0; i < result.snapshotLength; i++) {
     result.snapshotItem(i).parentElement.parentElement.parentElement.remove()
}
`
Ugly - but it works. Not sure why they (FAB/Epic) make customers life so hard! Everybody has a collection of assets and usually does NOT want to see them again on the website
