### ISSUE TITLE
Feature Request: Bring back Technical Details

### ISSUE THREAD

**Issue by xcpttrips** [Linj1k/fab_extended#3]
On the UE Marketplace, the "Technical Details" section was part of the product page, while with Fab, it is two extra clicks away.
An option for the extension to read the content of the "Technical Details" tab in the "See Details" popup and inject that text below the Description (above "Included formats") would be a nice addition.

**Comment by Linj1k** [comment]
With a little digging, I think it's possible

**Comment by Linj1k** [comment]
Hello,
I've added your feature, but we'll have to wait for the Chrome Web Store to validate it.
