### ISSUE TITLE
Feature Request: Add To Cart button on search results

### ISSUE THREAD

**Issue by xcpttrips** [Linj1k/fab_extended#4]
Problem: Search results on the UE Marketplace had a convenient Add To Cart button, while on Fab, each product has to be opened in a new page first.
Solution: Inject an Add To Cart button on search results elements.

**Comment by Linj1k** [comment]
It's not a stupid idea,
There are so many things that Epic have removed or forgotten about Fab

I think this is possible, now we'll have to see how the basket tab behaves if the item appears in it.

**Comment by Linj1k** [comment]
Hello,
I've added your feature, but we'll have to wait for the Chrome Web Store to validate it.
