### ISSUE TITLE
[Bug | Regression] Favorites: Add to Fav Icon missing on Product Page 

### ISSUE THREAD

**Issue by xcpttrips** [Linj1k/fab_extended#6]
Previously, there was a Fav Icon to the left of the product title on any product page (outline when not added, filled red when added).
Currently this icon is missing and product can't be added to Favs from here.

Also, previously this icon only worked to add products to Favs but not to remove them.
It would be preferable if clicking on a red Fav icon removed the current product from Favs.

**Comment by Linj1k** [comment]
Hello,

I've made a lot of changes, I noticed this problem that is already fixed and will soon be updated on the Chrome Web Store.

**Comment by xcpttrips** [comment]
Figured it's a known issue, wanted to mention it just in case.

**Comment by xcpttrips** [comment]
Icon is now visible.
