### ISSUE TITLE
[Feature Request] Add Open Favs option to show as new Tab

### ISSUE THREAD

**Issue by xcpttrips** [Linj1k/fab_extended#7]
Presently, when hovering over the Fav icon in the top navigation, Favs show as a popup.
This is a good choice for quick access, but an additional "Show in New Tab" option would be preferrable to be able to review favorites more thoroughly (e.g. scrolling through huge list and opening some products without closing the list).

It basically would need a button in the popup "Review Favorites" or "Open Favorites in New Tab" - or - open in new tab could be the click option for the icon (hover: show current popup; click: open as page in new tab.

**Comment by Linj1k** [comment]
That's a good idea. For your information, you already have the option of viewing favorites outside fab, directly by clicking on the extension icon in the browser.

**Comment by Linj1k** [comment]
That done, I've also added a search bar,
I'll make a few other changes before sending it off as an update
