### ISSUE TITLE
[Feature Request] Link Grabber for Product Description

### ISSUE THREAD

**Issue by xcpttrips** [Linj1k/fab_extended#8]
Video links as the first items in the screenshot area are common on the Unity Asset store, Steam, etc. yet, Epic never came around to add that feature. They mentioned somewhere that they want to remedy that, but even then (when / if), it would likely be up to the publishers to actually utilize that and many will leave them as part of the description. The lack of any standardization where those are placed makes it kinda irritating to look for them.

#1. So, first idea would be to get any video links from the description (youtube.com, youtu.be, vimeo.com) and ideally add them to the front of screenshot URLs and open/play in the area of the selected screenshot (this might not be doable at all or labor intensive I imagine), 

or alternatively:

Embed the video below the respective link  into the description, where it would immediately stick out.

(Note: for playlists it would be better to use a Youtube Logo image and onclick open it in a new tab - as embedded playlists will just look like a regular video otherwise ).

#2. As a second part of this idea (and why I called it Link Grabber instead of something video specific):
Maybe also grab any and all external URLs from the description and list them in an area above or below "technical details" for easier access (some publishers place links at the top, others at the bottom or somewhere inbetween. Chaos. Madness.
An area like this would make things much more organized.

Approach #2 would also work on its own without #1, though #1 would look cooler and allow for quicker access.

**Comment by Linj1k** [comment]
I've successfully added the videos to the product carousel, but I don't think an area with all the links would be useful. That's what the description is for

**Comment by xcpttrips** [comment]
You are right, the URL area isn't all that important and it might run into some edge cases anyways.

Do you have a solution or idea for YT playlists? I'm a bit worried those might show up as a single video without any way to know they are supposed to be playlists (at least i think they look the same as a single video when embded somewhere). 
It probably would suffice if the thumbnail in the carrousel had some distinguishable feature (icon, color).

**Comment by Linj1k** [comment]
I've added an icon to differentiate

**Comment by xcpttrips** [comment]
I'm amazed how well it all comes together.
This is such great work!

**Comment by Linj1k** [comment]
Yes, I'm very happy to see the result
Thank you for your ideas

**Comment by xcpttrips** [comment]
Looks like Epic added a confirmation for external content:

![image](https://github.com/user-attachments/assets/5d03540d-e2f4-4db6-ba1b-72e5ce79c1da)

At least for me, the choice isn't being saved and I need to reapprove on each video. This might be something they will fix and if it remembers the choice then, this shouldn't be too annoying. 

Probably nothing that can be done about it in the extension.

It also seems to have removed the Youtube icon overlay from the thumbnail in the carrousel, no idea why.

**Comment by Linj1k** [comment]
I don't have this confirmation yet, so it may take some time for it to be set up in my area

**Comment by xcpttrips** [comment]
Seems to be working as before again.
This wasn't just a single PC either, btw, 
I tested it on 2 workstations with Chrome and Edge.

This is how the thumbnails looked (the confirmation prompt was there, too:

![image](https://github.com/user-attachments/assets/cb219796-78a9-4e24-9a95-21d5df0c476c)

It switched back to normal within the last 15-30 minutes - let's hope it stays that way.

Presently:

![image](https://github.com/user-attachments/assets/623f97c9-9715-4987-8001-4e31a22c7c5f)
